name: build and test

# Controls when the workflow will run
on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  workflow_dispatch:


env:
  isProduction: 'false'
  MAJOR_VERSION: 4
  MINOR_VERSION: 0
  PATCH_VERSION: 1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: Npm ci
        run: npm ci

      - name: Npm run lint
        run: npm run lint

      - name: Npm run test
        run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Jest Test Results
          path: ./*.xml
          reporter: jest-junit
          only-summary: 'true'

      - name: Npm run build
        run: npm run build

      - name: Npm run generate-doc
        run: npm run generate-doc

      - name: store versions to txt files
        run: |
          echo ${{ env.MAJOR_VERSION }}.${{ env.MAJOR_VERSION }}.${{ env.PATCH_VERSION }} > production_version.txt
          echo  ${{ env.MAJOR_VERSION }}.${{ env.MAJOR_VERSION }}.${{ env.PATCH_VERSION }}--preview-${{ github.run_id }} > preview_version.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./.npmrc
            ./README.md
            ./LICENSE
            ./production_version.txt
            ./preview_version.txt
