name: build-and-publish

# Controls when the workflow will run
on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  workflow_dispatch:

   
env:
  isProduction: 'false'
  MAJOR_VERSION: 3
  MINOR_VERSION: 0
  PATCH_VERSION: 5

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: Npm ci
        run: npm ci

      - name: Npm run lint
        run: npm run lint

      - name: Npm run test
        run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Jest Test Results
          path: ./*.xml
          reporter: jest-junit
          only-summary: 'true'

      - name: Npm run build
        run: npm run build

      - name: Npm run generate-doc
        run: npm run generate-doc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./.npmrc
            ./README.md
            ./LICENSE
            
  preview:
    runs-on: ubuntu-latest
    environment: preview
    if: ${{ github.run_attempt != 1 }}
    needs: [ build ]
    steps:

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: set up variable -- NpmPackageVersion
        run: echo "NpmPackageVersion=${{env.MAJOR_VERSION}}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact
          
      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

  production:
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt != 1 }}
    environment: production
    needs: [ build, preview ]
    steps:
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
          
      - name: Npm tool install
        run: npm install -g npm@8

      - name: set up variable -- NpmPackageVersion
        run: echo "NpmPackageVersion=${{env.MAJOR_VERSION}}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}" >> $GITHUB_ENV
        
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact
          
      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }} 
