name: lf-js-utils-CI

on:
  push:
    branches: [ '^\d+.x$' ]
  pull_request:
    branches: [ '^\d+.x$' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publishProduction:
        description: 'Publish to npm production'
        type: boolean
        required: true
        default: 'false'
      publishPreview:
        description: 'Publish to npm preview'
        type: boolean
        required: true
        default: 'false'

env:
  MAJOR_VERSION: 3
  MINOR_VERSION: 0
  PATCH_VERSION: 1
  publishProduction: 'false'
  publishPreview: 'false'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy
    outputs:
      NpmTag: ${{ env.NpmTag }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version:  '14.x'

      - name: Npm ci
        run: npm ci

      - name: Npm run lint
        run: npm run lint
  
      - name: Npm run test
        run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Test
          path: ./*.xml
          reporter: jest-junit
          only-summary: 'true'

      - name: Npm run build
        run: npm run build
        
      - name: set up variable -- NpmPackageVersion and NpmTag for prod
        if: ${{ github.event.inputs.publishProduction == 'true'}}
        run: |
          echo "NpmPackageVersion=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}" >> $GITHUB_ENV
          echo "NpmTag='latest'" >> $GITHUB_ENV
        
      - name: Set up variable -- NpmPackageVersion and NpmTag for preview
        if: ${{ github.event.inputs.publishPreview == 'true'}}
        run: |
          echo "NpmPackageVersion=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
          echo "NpmTag='next'" >> $GITHUB_ENV
        
      - name: Echo NPM package version
        run: echo ${{ env.NpmPackageVersion }}
        
      - name: Npm version
        if: ${{ env.NpmPackageVersion }}
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./.npmrc

  publishNPM:
    runs-on: ubuntu-latest
    environment: publish
    needs: [ build ] # wait for build to finish
    if: ${{  github.event.inputs.publishPreview == 'true' || github.event.inputs.publishProduction == 'true' }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: Npm publish
        run: npm publish  --access public  --tag ${{ needs.build.outputs.NpmTag }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
