# This is a basic workflow to help you get started with Actions

name: Build
# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAJOR_VERSION: 2
  MINOR_VERSION: 0
  PATCH_VERSION: 2


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: 'Echo major'
        run: echo "$MAJOR_VERSION"

      - name: 'Echo build number'
        run: echo "${{github.run_id}}"

      - name: 'Echo NPM package version'
        run: echo "$NpmPackageVersion"
        env:
          CURRENT_VERSION: ${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{env.PATCH_VERSION}}
          NpmPackageVersion: ${{env.CURRENT_VERSION}}-preview-${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version:  '14.x'


#       - name: 'npm install'
#         run: 'npm install'

#       - name: 'npm run lint'
#         run: 'npm run lint'

#       - name: npm run test
#         run: 'npm run test:ci'



