name: lf-js-utils-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NPM_VERSION: "4.0.1"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy


    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: Npm ci
        run: npm ci

      - name: Npm run lint
        run: npm run lint

      - name: Npm run test
        run: npm run test:ci
        
      - name: echo github fork
        run: echo  ${{ github.event.pull_request.head.repo.fork }}
        
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() && ${{ github.event.pull_request.head.repo.fork == 'false' }}  # fork pr does not permission to write to checks
        with:
          name: Jest Test Results
          path: ./*.xml
          reporter: jest-junit
          only-summary: 'true'
          fail-on-error: 'false'
          
      - name: Npm run build
        run: npm run build

      - name: Npm run generate-doc
        run: npm run generate-doc

      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./.npmrc
            ./README.md
            ./LICENSE
      - name: echo github run attempt
        run: echo ${{ github.run_attempt }} ${{  github.event.pull_request.head.repo.owner.login }}


  publish_to_npm_preview:
    runs-on: ubuntu-latest
    environment: npm_preview
    if: ${{ (github.run_attempt != 1 && github.event.pull_request.head.repo.owner.login == 'Laserfiche') || (github.run_attempt != 2 && github.event.pull_request.head.repo.owner.login != 'Laserfiche') }}
    needs: [ build ] # wait for build to finish
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: set NpmPackageVersion environment
        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        
      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NpmPackageVersion }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}} 

  publish_to_npm_release:
    runs-on: ubuntu-latest
    environment: npm_production
    if: ${{ (github.run_attempt != 1 && github.event.pull_request.head.repo.owner.login == 'Laserfiche') || (github.run_attempt != 2 && github.event.pull_request.head.repo.owner.login != 'Laserfiche') }}
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: npm version
        run: npm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NPM_VERSION }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}} 
