name: lf-js-utils-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NPM_VERSION: "4.0.1"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: Npm ci
        run: npm ci

      - name: Npm run lint
        run: npm run lint

      - name: Npm run test
        run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Jest Test Results
          path: ./*.xml
          reporter: jest-junit
          only-summary: 'true'
          fail-on-error: 'false'

      - name: Npm run build
        run: npm run build

      - name: Npm run generate-doc
        run: npm run generate-doc

      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./.npmrc
            ./README.md
            ./LICENSE

  publish_to_npm_preview:
    runs-on: ubuntu-latest
    environment: npm_preview
    if: ${{ github.run_attempt != 1 }}
    needs: [ build ] # wait for build to finish
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: set NpmPackageVersion environment
        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        
      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NpmPackageVersion }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}} 

  publish_to_npm_release:
    runs-on: ubuntu-latest
    environment: npm_production
    if: ${{ github.run_attempt != 1 }}
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: npm version
        run: npm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NPM_VERSION }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}} 
          
  delete_preview_package_and_tag:
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt != 1 }}
    needs: [ build ]
    outputs:
      empty_matrix: ${{ steps.check-matrix.outputs.empty_matrix }}
      NpmPackageName: ${{ env.NpmPackageName }}
      NpmPackageVersionFiltered: ${{ steps.set-matrix-filtered.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          
      - name: Set NpmPackageName
        run: |
          SHOWNAME=$(npm view . name)
          echo "NpmPackageName=$SHOWNAME" >> $GITHUB_ENV
          
      - name: echo NpmPackageName
        run: echo ${{ env.NpmPackageName }}
          
      - name: Set NpmVersionsArrayFiltered
        id: set-matrix-filtered
        run: |
          \node ./clean_up_filter_npm_versions.cjs ${{env.NpmPackageName}} ${{ env.NPM_VERSION }} > matching_version.txt
          echo "::set-output name=matrix::$(cat matching_version.txt)"
          
      - id: check-matrix
        name: Check matrix      
        run: |
          if [[ ${{ steps.set-matrix-filtered.outputs.matrix }} == *"[]"* ]]; then
            echo "::set-output name=empty_matrix::true"
          else
            echo "::set-output name=empty_matrix::false"   
          fi
        
        
  delete_preview_package:
      runs-on: ubuntu-latest
      environment: remove_npm_packages
      needs: [ delete_preview_package_and_tag ]
      if: ${{ needs.delete_preview_package_and_tag.outputs.empty_matrix == 'false' }}
      strategy:
        matrix:
          version: ${{ fromJSON(needs.delete_preview_package_and_tag.outputs.NpmPackageVersionFiltered) }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.sha }}
      
        - name: check if npm package already deprecated
          id: check-deprecation
          run: |
            \node ./check_if_npm_package_deprecated.cjs ${{needs.delete_preview_package_and_tag.outputs.NpmPackageName}} ${{  matrix.version }} > already_deprecated.txt
            echo "::set-output name=deprecated::$(cat already_deprecated.txt)"
            
        - name: Npm deprecate preview package
          if: ${{ steps.check-deprecation.outputs.deprecated == 'false' }}
          run: npm deprecate -f ${{ needs.delete_preview_package_and_tag.outputs.NpmPackageName }}@${{ matrix.version }} "This version has been deprecated. Please upgrade to ${{env.NPM_VERSION}} instead."
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
            NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
            NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        
        
        - name: Delete prelease tag
          uses: dev-drprasad/delete-tag-and-release@v0.2.0
          with:
            delete_release: false
            tag_name: ${{  matrix.version }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
