name: new

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NPM_VERSION: "4.0.1"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy


    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Echo hello
        run: echo hello
